version: '2'

services:
  db:
    image: postgres
    env_file: ./production.env
    restart: always
    volumes:
     - ./volumes/pgdata:/var/lib/postgresql/data
  web:
    build:
      context: ../
      dockerfile: docker/web/Dockerfile
    env_file: ./production.env
    restart: always
    command: web
    depends_on:
      - db
    volumes:
      - ./volumes/upload:/upload
      - ./volumes/static:/static
  nginx:
    image: nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./volumes/static:/var/www/static
