version: '2'

services:
  db:
    image: postgres
    env_file: ./production.env
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: ./web
    env_file: ./production.env
    restart: always
    command: web
    depends_on:
      - db
    ports:
      - "127.0.0.1:8001:80"
    volumes:
      - drapo-upload:/upload

volumes:
    drapo-upload:
    pgdata:
